version: '3.8'

services:
  assessment:
    image: mrksdh/assessment  # Hier wird Ihr Assessment-Image verwendet
    ports:
      - "8080:8080"  # Exponieren des Ports 8080

  nils:
    build:
      context: .  # Der aktuelle Kontext für den Build
      dockerfile: Dockerfile  # Dein Dockerfile für den Nils-Dienst
    depends_on:
      - assessment  # Wartet, bis der Assessment-Dienst gestartet ist

